---------------------------------------
-- TABLES
---------------------------------------

CREATE TABLE "{0}"."cl_language" (
	"id" varchar(2) NOT NULL,
	"active" bool DEFAULT false,
	"ready" bool DEFAULT false,
	"en" text,
  	"de" text,
  	"fr" text,
  	"es" text,
  	"it" text,
  	"sk" text,
	PRIMARY KEY ("id")
);

CREATE TABLE "{0}"."tbl_app" (
	"id" text NOT NULL,
	"name" text,
	"icon" text,
  	"url" text,
	"path" text,
	PRIMARY KEY ("id")
);

CREATE TABLE "{0}"."tbl_translation" (
	"id" text NOT NULL,
	"app" text NOT NULL,
	"hash" text NOT NULL,
	"text" text,
	"deferr" bool DEFAULT false,
	"en" text,
  	"de" text,
  	"fr" text,
  	"es" text,
  	"it" text,
  	"sk" text,
	PRIMARY KEY ("id")
);

---------------------------------------
-- DATA
---------------------------------------

INSERT INTO "{0}"."cl_language" ("id", "active", "ready", "en", "de", "fr", "es", "it", "sk") VALUES
('ce', false, false, 'Chechen', 'Tschetschenisch', 'Tchétchène', 'Checheno', 'Ceceno', 'Čečenský'),
('bs', false, false, 'Bosnian', 'Bosnisch', 'Bosniaque', 'Bosnio', 'Bosniaco', 'Bosniansky'),
('ch', false, false, 'Chamorro', 'Chamorro-Sprache', 'Chamorro', 'Chamorro', 'Chamorro', 'Chamorro'),
('br', false, false, 'Breton', 'Bretonisch', 'Breton', 'Bretón', 'Bretone', 'Breton'),
('ca', false, false, 'Catalan', 'Katalanisch', 'Catalan', 'Catalán', 'Catalano', 'Katalánsky'),
('co', false, false, 'Corsican', 'Korsisch', 'Corse', 'Corso', 'Corso', 'Korzické'),
('cr', false, false, 'Cree', 'Cree-Sprache', 'Cree', 'Cree', 'Cree', 'Cree'),
('kv', false, false, 'Komi', 'Komi-Sprache', 'Kom', 'Komi', 'Komi', 'Komi'),
('ky', false, false, 'Kirghiz', 'Kirgisisch', 'Kirghiz', 'Kirguís', 'Chirghiso', 'Kirgizština'),
('lb', false, false, 'Luxembourgish', 'Luxemburgisch', 'Luxembourgeois', 'Luxemburgués', 'Lussemburghese', 'Luxemburský'),
('li', false, false, 'Limburgish', 'Limburgisch', 'Limbourgeois', 'Limburgués', 'Limburghese', 'Limburský'),
('kw', false, false, 'Cornish', 'Kornisch', 'Cornique', 'Córnico', 'Cornico', 'Cornish'),
('la', false, false, 'Latin', 'Latein', 'Latin', 'Latín', 'Latino', 'Latinčina'),
('lg', false, false, 'Ganda', 'Ganda-Sprache', 'Ganda', 'Luganda', 'Luganda', 'Ganda'),
('ln', false, false, 'Lingala', 'Lingala', 'Lingala', 'Lingala', 'Lingala', 'Lingala'),
('lo', false, false, 'Lao', 'Laotisch', 'Lao', 'Lao', 'Lao', 'Lao'),
('lt', false, false, 'Lithuanian', 'Litauisch', 'Lituanien', 'Lituano', 'Lituano', 'Litovský'),
('te', false, false, 'Telugu', 'Telugu-Sprache', 'Télougou', 'Telugú', 'Telugu', 'Telugčina'),
('tg', false, false, 'Tajik', 'Tadschikisch', 'Tadjik', 'Tayiko', 'Tagiko', 'Tadžický'),
('th', false, false, 'Thai', 'Thailändisch', 'Thaï', 'Tailandés', 'Thailandese', 'Thajčina'),
('ti', false, false, 'Tigrinya', 'Tigrinja-Sprache', 'Tigrigna', 'Tigriña', 'Tigrino', 'Tigrinya'),
('tk', false, false, 'Turkmen', 'Turkmenisch', 'Turkmène', 'Turcomano', 'Turkmeno', 'Turkménskym'),
('tl', false, false, 'Tagalog', 'Tagalog', 'Tagalog', 'Tagalo', 'Tagalog', 'Tagalog'),
('tn', false, false, 'Tswana', 'Tswana-Sprache', 'Tswana', 'Setsuana', 'Tswana', 'Tswana'),
('to', false, false, 'Tonga', 'Tongaisch', 'Tongan', 'Tongano', 'Tongano', 'Tonga'),
('tr', false, false, 'Turkish', 'Türkisch', 'Turc', 'Turco', 'Turco', 'Turecký'),
('ts', false, false, 'Tsonga', 'Tsonga-Sprache', 'Tsonga', 'Tsonga', 'Tsonga', 'Tsonga'),
('tt', false, false, 'Tatar', 'Tatarisch', 'Tatar', 'Tártaro', 'Tataro', 'Tatársky'),
('ku', false, false, 'Kurdish', 'Kurdisch', 'Kurde', 'Kurdo', 'Curdo', 'Kurdský'),
('aa', false, false, 'Afar', 'Danakil-Sprache', 'Afar', 'Afar', 'Afar', 'Afar'),
('uz', false, false, 'Uzbek', 'Usbekisch', 'Ouszbek', 'Uzbeko', 'Usbeco', 'Uzbecký'),
('ur', false, false, 'Urdu', 'Urdu', 'Ourdou', 'Urdu', 'Urdu', 'Urdčina'),
('uk', false, false, 'Ukrainian', 'Ukrainisch', 'Ukrainien', 'Ucraniano', 'Ucraino', 'Ukrajinčina'),
('ug', false, false, 'Uighur', 'Uigurisch', 'Ouïgour', 'Uigur', 'Uiguro', 'Ujgurské'),
('bo', false, false, 'Tibetan', 'Tibetisch', 'Tibétain', 'Tibetano', 'Tibetano', 'Tibetský'),
('bn', false, false, 'Bengali', 'Bengali', 'Bengali', 'Bengalí', 'Bengalese', 'Bengálsky'),
('gu', false, false, 'Gujarati', 'Gujarati-Sprache', 'Goudjrati', 'Guyaratí', 'Gujarati', 'Gudžarátčina'),
('ta', false, false, 'Tamil', 'Tamil', 'Tamoul', 'Tamil', 'Tamil', 'Tamilčina'),
('sw', false, false, 'Swahili', 'Swahili', 'Swahili', 'Suajili', 'Swahili', 'Svahilčina'),
('sv', false, false, 'Swedish', 'Schwedisch', 'Suédois', 'Sueco', 'Svedese', 'Švédsky'),
('su', false, false, 'Sundanese', 'Sundanesisch', 'Soundanais', 'Sundanés', 'Sondanese', 'Sundánsky'),
('fa', false, false, 'Persian', 'Persisch', 'Persan', 'Persa', 'Persiano, Fārsì', 'Perzský'),
('et', false, false, 'Estonian', 'Estnisch', 'Estonien', 'Estonio', 'Estone', 'Estónsky'),
('eo', false, false, 'Esperanto', 'Esperanto', 'Espéranto', 'Esperanto', 'Esperanto', 'Esperanto'),
('ba', false, false, 'Bashkir', 'Baschkirisch', 'Bachkir', 'Baskir', 'Bashkir', 'Bashkir'),
('tw', false, false, 'Twi', 'Twi-Sprache', 'Twi', 'Twi', 'Twi', 'Twi'),
('dv', false, false, 'Maldivian', 'Maledivisch', 'Maldivien', 'Maldivo', 'Divehi, Dhivehi, Maldiviano', 'Maldivský'),
('el', false, false, 'Greek', 'Neugriechisch', 'Grec Moderne', 'Griego', 'Greco, moderno', 'Grécky'),
('cv', false, false, 'Chuvash', 'Tschuwaschisch', 'Tchouvache', 'Chuvasio', 'Ciuvascio', 'Čuvašský'),
('cy', false, false, 'Welsh', 'Kymrisch', 'Gallois', 'Galés', 'Gallese', 'Waleský'),
('cu', false, false, 'Old Slavonic', 'Kirchenslawisch', 'Vieux Slave', 'Eslavo Eclesiástico Antiguo', 'Antico slavo ecclesiastico', 'Staroslovienčina'),
('cs', false, false, 'Czech', 'Tschechisch', 'Tchèque', 'Checo', 'Ceco', 'Český'),
('da', false, false, 'Danish', 'Dänisch', 'Danois', 'Danés', 'Danese', 'Dánčina'),
('ab', false, false, 'Abkhazian', 'Abchasisch', 'Abkhaze', 'Abjaso', 'Abkhaz', 'Abcházsky'),
('ee', false, false, 'Ewe', 'Ewe-Sprache', 'Éwé', 'Ewe', 'Ewe', 'Ewe'),
('de', true, false, 'German', 'Deutsch', 'Allemand', 'Alemán', 'Tedesco', 'Nemecký'),
('dz', false, false, 'Dzongkha', 'Dzongkha', 'Dzongkha', 'Dzongkha', 'Dzongkha', 'Dzongkha'),
('oj', false, false, 'Ojibwa', 'Ojibwa-Sprache', 'Ojibwa', 'Ojibwa', 'Ojibwa', 'Ojibwa'),
('ny', false, false, 'Nyanja', 'Nyanja-Sprache', 'Nyanja', 'Chichewa', 'Nyanja', 'Nyanja'),
('wo', false, false, 'Wolof', 'Wolof-Sprache', 'Wolof', 'Wolof', 'Wolof', 'Wolof'),
('wa', false, false, 'Walloon', 'Wallonisch', 'Wallon', 'Valón', 'Vallone', 'Valónsky'),
('be', false, false, 'Belarusian', 'Weißrussisch', 'Biélorusse', 'Bielorruso', 'Bielorusso', 'Bieloruský'),
('bm', false, false, 'Bambara', 'Bambara-Sprache', 'Bambara', 'Bambara', 'Bambara', 'Bambara'),
('bi', false, false, 'Bislama', 'Beach-la-mar', 'Bichlamar', 'Bislama', 'Bislama', 'Bislama'),
('bg', false, false, 'Bulgarian', 'Bulgarisch', 'Bulgare', 'Búlgaro', 'Bulgaro', 'Bulharčina'),
('az', false, false, 'Azerbaijani', 'Aserbeidschanisch', 'Azéri', 'Azerí', 'Azero', 'Azerbajdžanský'),
('se', false, false, 'Northern Sami', 'Nordsaamisch', 'Sami Du Nord', 'Sami Septentrional', 'Sami settentrionale', 'Severný Sami'),
('rn', false, false, 'Rundi', 'Rundi-Sprache', 'Rundi', 'Kirundi', 'Kirundi', 'Rundi'),
('ru', false, false, 'Russian', 'Russisch', 'Russe', 'Ruso', 'Russo', 'Ruský'),
('ro', false, false, 'Romanian', 'Rumänisch', 'Roumain', 'Rumano', 'Rumeno', 'Rumunský'),
('qu', false, false, 'Quechua', 'Quechua-Sprache', 'Quechua', 'Quechua', 'Quechua', 'Kečuánsky'),
('pt', false, false, 'Portuguese', 'Portugiesisch', 'Portugais', 'Portugués', 'Portoghese', 'Portugalčina'),
('ps', false, false, 'Pashto', 'Paschtu', 'Pachto', 'Pashto', 'Pashtu', 'Paštčina'),
('gn', false, false, 'Guarani', 'Guaraní-Sprache', 'Guarani', 'Guaraní', 'Guaraní', 'Guarani'),
('ty', false, false, 'Tahitian', 'Tahitisch', 'Tahitien', 'Tahitiano', 'Tahitiano', 'Tahitský'),
('eu', false, false, 'Basque', 'Baskisch', 'Basque', 'Vascuence', 'Basco', 'Baskický'),
('xh', false, false, 'Xhosa', 'Xhosa-Sprache', 'Xhosa', 'Xhosa', 'Xhosa', 'Xhosa'),
('sa', false, false, 'Sanskrit', 'Sanskrit', 'Sanskrit', 'Sánscrito', 'Sanscrito', 'Sanskrit'),
('pl', false, false, 'Polish', 'Polnisch', 'Polonais', 'Polaco', 'Polacco', 'Poľský'),
('en', true, true, 'English', 'Englisch', 'Anglais', 'Inglés', 'Inglese', 'Angličtina'),
('om', false, false, 'Oromo', 'Galla-Sprache', 'Galla', 'Oromo', 'Oromo', 'Oromo'),
('or', false, false, 'Oriya', 'Oriya-Sprache', 'Oriya', 'Oriya', 'Oriya', 'Oriya'),
('oc', false, false, 'Occitan', 'Okzitanisch', 'Occitan', 'Occitano', 'Occitano', 'Okcitánsky'),
('nv', false, false, 'Navajo', 'Navajo-Sprache', 'Navaho', 'Navajo', 'Navajo, Navaho', 'Navajo'),
('vo', false, false, 'Volapük', 'Volapük', 'Volapük', 'Volapük', 'Volapük', 'Volapük'),
('vi', false, false, 'Vietnamese', 'Vietnamesisch', 'Vietnamien', 'Vietnamita', 'Vietnamita', 'Vietnamci'),
('rm', false, false, 'Romansh', 'Rätoromanisch', 'Romanche', 'Retorrománico', 'Romancio', 'Rétorománčina'),
('nr', false, false, 'South Ndebele', 'Ndebele-Sprache (Transvaal)', 'Ndébélé Du Sud', 'Ndebele Del Sur', 'Ndebele del Sud', 'Južné Ndebele'),
('sc', false, false, 'Sardinian', 'Sardisch', 'Sarde', 'Sardo', 'Sardo', 'Sardínsky'),
('ve', false, false, 'Venda', 'Venda-Sprache', 'Venda', 'Venda', 'Venda', 'Venda'),
('rw', false, false, 'Kinyarwanda', 'Rwanda-Sprache', 'Rwanda', 'Ruandés', 'Kinyarwanda', 'Kinyarwanda'),
('sd', false, false, 'Sindhi', 'Sindhi-Sprache', 'Sindhi', 'Sindhi', 'Sindhi', 'Sindhi'),
('no', false, false, 'Norwegian', 'Norwegisch', 'Norvégien', 'Noruego', 'Norvegese', 'Nórsky'),
('sg', false, false, 'Sango', 'Sango-Sprache', 'Sango', 'Sango', 'Sango', 'Sango'),
('es', true, true, 'Spanish', 'Spanisch', 'Espagnol', 'Español', 'Spagnolo, Castigliano', 'Španielčina'),
('ay', false, false, 'Aymara', 'Aymará-Sprache', 'Aymara', 'Aimara', 'Aymara', 'Aymara'),
('ae', false, false, 'Avestan', 'Avestisch', 'Avestique', 'Avéstico', 'Avestico', 'Avestan'),
('ho', false, false, 'Hiri Motu', 'Hiri-Motu', 'Hiri Motu', 'Hiri Motu', 'Hiri Motu', 'Hiri Motu'),
('he', false, false, 'Hebrew', 'Hebräisch', 'Hébreu', 'Hebreo', 'Ebraico (moderno)', 'Hebrejčina'),
('gv', false, false, 'Manx', 'Manx', 'Manx, Mannois', 'Manés', 'Mannese', 'Manx'),
('pa', false, false, 'Punjabi', 'Pandschabi-Sprache', 'Pendjabi', 'Panyabí', 'Punjabi', 'Pandžábsky'),
('pi', false, false, 'Pali', 'Pali', 'Pali', 'Pali', 'Pāli', 'Pali'),
('ia', false, false, 'Interlingua', 'Interlingua', 'Interlingua', 'Interlingua', 'Interlingua', 'Interlingua'),
('kg', false, false, 'Kongo', 'Kongo-Sprache', 'Kongo', 'Kongo', 'Kikongo', 'Kongo'),
('jv', false, false, 'Javanese', 'Javanisch', 'Javanais', 'Javanés', 'Giavanese', 'Jávsky'),
('iu', false, false, 'Inuktitut', 'Inuktitut', 'Inuktitut', 'Inuktitut', 'Inuktitut', 'Inuktitut'),
('is', false, false, 'Icelandic', 'Isländisch', 'Islandais', 'Islandés', 'Islandese', 'Islandský'),
('ik', false, false, 'Inupiaq', 'Inupik', 'Inupiaq', 'Inupiaq', 'Inupiaq', 'Inupiaq'),
('ig', false, false, 'Igbo', 'Ibo-Sprache', 'Igbo', 'Igbo', 'Igbo', 'Igbo'),
('ha', false, false, 'Hausa', 'Haussa-Sprache', 'Haoussa', 'Hausa', 'Hausa', 'Hausa'),
('hi', false, false, 'Hindi', 'Hindi', 'Hindi', 'Hindi', 'Hindi', 'Hindčina'),
('hr', false, false, 'Croatian', 'Kroatisch', 'Croate', 'Croata', 'Croato', 'Chorvátsky'),
('ht', false, false, 'Haitian', 'Haïtien', 'Haïtien', 'Haitiano', 'Creolo haitiano', 'Haitský'),
('hu', false, false, 'Hungarian', 'Ungarisch', 'Hongrois', 'Húngaro', 'Ungherese', 'Maďarský'),
('hy', false, false, 'Armenian', 'Armenisch', 'Arménien', 'Armenio', 'Armeno', 'Arménsky'),
('hz', false, false, 'Herero', 'Herero-Sprache', 'Herero', 'Herero', 'Herero', 'Herero'),
('id', false, false, 'Indonesian', 'Bahasa Indonesia', 'Indonésien', 'Indonesio', 'Indonesiano', 'Indonézsky'),
('ie', false, false, 'Interlingue', 'Interlingue', 'Interlingue', 'Occidental', 'Interlingue', 'Interlingue'),
('ii', false, false, 'Sichuan Yi', 'Lalo-Sprache', 'Yi De Sichuan', 'Yi De Sichuán', 'Nuosu', 'Sichuan Yi'),
('io', false, false, 'Ido', 'Ido', 'Ido', 'Ido', 'Ido', 'Ido'),
('it', true, false, 'Italian', 'Italienisch', 'Italien', 'Italiano', 'Italiano', 'Taliansky'),
('os', false, false, 'Ossetic', 'Ossetisch', 'Ossète', 'Osético', 'Osseto', 'Ossetic'),
('ja', false, false, 'Japanese', 'Japanisch', 'Japonais', 'Japonés', 'Giapponese', 'Japončina'),
('ka', false, false, 'Georgian', 'Georgisch', 'Géorgien', 'Georgiano', 'Georgiano', 'Gruzínsky'),
('nd', false, false, 'North Ndebele', 'Ndebele-Sprache (Simbabwe)', 'Ndébélé Du Nord', 'Ndebele Del Norte', 'Ndebele del Nord', 'Severné Ndebele'),
('nb', false, false, 'Norwegian', 'Bokmål', 'Norvégien Bokmål', 'Noruego Bokmål', 'Norvegese', 'Nórsky'),
('na', false, false, 'Nauru', 'Nauruanisch', 'Nauruan', 'Nauruano', 'Nauruano', 'Nauru'),
('my', false, false, 'Burmese', 'Birmanisch', 'Birman', 'Birmano', 'Birmano', 'Barmský'),
('mt', false, false, 'Maltese', 'Maltesisch', 'Maltais', 'Maltés', 'Maltese', 'Maltčina'),
('ms', false, false, 'Malay', 'Malaiisch', 'Malais', 'Malayo', 'Malese', 'Malajčina'),
('mr', false, false, 'Marathi', 'Marathi', 'Marathe', 'Maratí', 'Marathi', 'Maráthčina'),
('mn', false, false, 'Mongolian', 'Mongolisch', 'Mongol', 'Mongol', 'Mongolo', 'Mongolský'),
('ml', false, false, 'Malayalam', 'Malayalam', 'Malayalam', 'Malayalam', 'Malayalam', 'Malajálamčina'),
('mk', false, false, 'Macedonian', 'Makedonisch', 'Macédonien', 'Macedonio', 'Macedone', 'Macedónsky'),
('mi', false, false, 'Maori', 'Maori-Sprache', 'Maori', 'Maorí', 'Maori', 'Maori'),
('mh', false, false, 'Marshallese', 'Marschallesisch', 'Marshall', 'Marshalés', 'Marshallese', 'Maršalský'),
('mg', false, false, 'Malagasy', 'Malagassi-Sprache', 'Malgache', 'Malgache', 'Malgascio', 'Malgašský'),
('lv', false, false, 'Latvian', 'Lettisch', 'Letton', 'Letón', 'Lettone', 'Lotyšský'),
('lu', false, false, 'Luba-Katanga', 'Luba-Katanga-Sprache', 'Luba-Katanga', 'Luba-Katanga', 'Luba-Katanga', 'Ľuba-Katanga'),
('sq', false, false, 'Albanian', 'Albanisch', 'Albanais', 'Albanés', 'Albanese', 'Albánsky'),
('nl', false, false, 'Dutch', 'Niederländisch', 'Néerlandais', 'Neerlandés', 'Olandese', 'Holandský'),
('ne', false, false, 'Nepali', 'Nepali', 'Népalais', 'Nepalí', 'Nepalese', 'Nepálsky'),
('nn', false, false, 'Norwegian Nynorsk', 'Nynorsk', 'Norvégien Nynorsk', 'Nynorsk', 'Norvegese Nynorsk', 'Nórsky Nynorsk'),
('sr', false, false, 'Serbian', 'Serbisch', 'Serbe', 'Serbio', 'Serbo', 'Srbský'),
('ng', false, false, 'Ndonga', 'Ndonga', 'Ndonga', 'Ndonga', 'Ndonga', 'Ndonga'),
('ss', false, false, 'Swati', 'Swasi-Sprache', 'Swati', 'Suazi', 'Swazi', 'Swati'),
('st', false, false, 'Southern Sotho', 'Süd-Sotho-Sprache', 'Sotho Du Sud', 'Sesotho', 'Sesotho del Sud', 'Južné Sotho'),
('gl', false, false, 'Galician', 'Galicisch', 'Galicien', 'Gallego', 'Galiziano', 'Haličský'),
('fj', false, false, 'Fijian', 'Fidschi-Sprache', 'Fidjien', 'Fijiano', 'Figiano', 'Fidžijský'),
('fo', false, false, 'Faroese', 'Färöisch', 'Féroïen', 'Feroés', 'Faroese', 'Faerské'),
('fi', false, false, 'Finnish', 'Finnisch', 'Finnois', 'Finés', 'Finlandese', 'Fínsky'),
('fy', false, false, 'Western Frisian', 'Friesisch', 'Frison Occidental', 'Frisón', 'Frisone occidentale', 'Západné Frízske'),
('fr', true, false, 'French', 'Französisch', 'Français', 'Francés', 'Francese', 'Francúzsky'),
('ff', false, false, 'Fulah', 'Ful', 'Peul', 'Fula', 'Fula, Fulah, Pulaar, Pular', 'Fulah'),
('ga', false, false, 'Irish', 'Irisch', 'Irlandais', 'Irlandés', 'Irlandese', 'Írsky'),
('gd', false, false, 'Gaelic', 'Gälisch-Schottisch', 'Gaélique', 'Gaélico Escocés', 'Gaelico scozzese', 'Galský'),
('ki', false, false, 'Kikuyu', 'Kikuyu-Sprache', 'Kikuyu', 'Kikuyu', 'Kikuyu, Gikuyu', 'Kikuyu'),
('kj', false, false, 'Kwanyama', 'Kwanyama-Sprache', 'Kwanyama', 'Kuanyama', 'Kuanyama', 'Kwanyama'),
('kk', false, false, 'Kazakh', 'Kasachisch', 'Kazakh', 'Kazajo', 'Kazaco', 'Kazašský'),
('kl', false, false, 'Greenlandic', 'Grönländisch', 'Groenlandais', 'Groenlandés', 'Groenlandese', 'Grónsky'),
('ko', false, false, 'Korean', 'Koreanisch', 'Coréen', 'Coreano', 'Coreano', 'Kórejský'),
('kr', false, false, 'Kanuri', 'Kanuri-Sprache', 'Kanouri', 'Kanuri', 'Kanuri', 'Kanuri'),
('km', false, false, 'Central Khmer', 'Kambodschanisch', 'Khmer Central', 'Camboyano', 'Khmer', 'Stredný Khmér'),
('kn', false, false, 'Kannada', 'Kannada', 'Kannada', 'Canarés', 'Kannada', 'Kannada'),
('ks', false, false, 'Kashmiri', 'Kaschmiri', 'Kashmiri', 'Cachemiro', 'Kashmiri', 'Kašmírsky'),
('af', false, false, 'Afrikaans', 'Afrikaans', 'Afrikaans', 'Afrikaans', 'Afrikaans', 'Afrikánčina'),
('yi', false, false, 'Yiddish', 'Jiddisch', 'Yiddish', 'Yiddish', 'Yiddish', 'Jidiš'),
('av', false, false, 'Avaric', 'Awarisch', 'Avar', 'Avar', 'Avaro', 'Avarický'),
('as', false, false, 'Assamese', 'Assamesisch', 'Assamais', 'Asamés', 'Assamese', 'Asámsky'),
('ar', false, false, 'Arabic', 'Arabisch', 'Arabe', 'Árabe', 'Arabo', 'Arabčina'),
('an', false, false, 'Aragonese', 'Aragonesisch', 'Aragonais', 'Aragonés', 'Aragonese', 'Aragónsky'),
('am', false, false, 'Amharic', 'Amharisch', 'Amharique', 'Amárico', 'Amarico', 'Amharčina'),
('ak', false, false, 'Akan', 'Akan-Sprache', 'Akan', 'Akano', 'Akan', 'Akan'),
('zu', false, false, 'Zulu', 'Zulu-Sprache', 'Zoulou', 'Zulú', 'Zulu', 'Zulu'),
('zh', false, false, 'Chinese', 'Chinesisch', 'Chinois', 'Chino', 'Cinese', 'Čínsky'),
('za', false, false, 'Zhuang', 'Zhuang', 'Zhuang', 'Zhuang', 'Zhuang', 'Zhuang'),
('yo', false, false, 'Yoruba', 'Yoruba-Sprache', 'Yoruba', 'Yoruba', 'Yoruba', 'Yoruba'),
('so', false, false, 'Somali', 'Somali', 'Somali', 'Somalí', 'Somalo', 'Somálsky'),
('sn', false, false, 'Shona', 'Schona-Sprache', 'Shona', 'Shona', 'Shona', 'Shona'),
('sm', false, false, 'Samoan', 'Samoanisch', 'Samoan', 'Samoano', 'Samoano', 'Samoan'),
('sl', false, false, 'Slovenian', 'Slowenisch', 'Slovène', 'Esloveno', 'Sloveno', 'Slovensky'),
('si', false, false, 'Sinhalese', 'Singhalesisch', 'Singhalais', 'Cingalés', 'Singalese', 'Sinhálčina'),
('sk', true, true, 'Slovak', 'Slowakisch', 'Slovaque', 'Eslovaco', 'Slovacco', 'Slovenský');


INSERT INTO "{0}"."tbl_app" ("id", "name", "icon", "url") VALUES
	('1', 'Translator', 'ti ti-language-alt', '');

